server:
  port: 8082

dubbo:
  application:
    name: crowdos-gateway-test
    version: 1.0.0
  registry:
    address: zookeeper://8.130.67.138:2181
  protocol:
    name: dubbo
    port: 20881
  scan:
    base-packages: cn.crowdos.gateway.rpc